### ISSUE TITLE
Encodings: verschil tussen uitwisselen in vaste ketens en aanbieden aan onbekende gebruikers toevoegen

### ISSUE THREAD

**Issue by frisopenninga** [Geonovum/bmgi#21]
Ik denk dat het zinvol is om het onderscheid te maken tussen uitwisselen in bestaande ketens (met bekende / expert-gebruikers) en aanbieden aan elke willekeurige datagebruiker: in de eerste situatie gaat het om zaken als controleerbaarheid, valideerbaarheid en rijkdom aan opties (specialisten kunnen daar immers mee omgaan), in de tweede situatie gaat het om verleiden tot gebruik door drempels voor gebruik weg te nemen. Dat gaat vaker om niet-experts, om minder complexe use cases en om use cases die niet om het allerhoogste kwaliteits-/betrouwbaarheidsniveau vragen. In https://geonovum.github.io/bmgi/docs/#inleiding-3 staan er nu use cases die voor beide categorieën kunnen gelden en zijn daardoor m.i. niet scherp genoeg om het onderscheid uit te leggen.

**Comment by lvdbrink** [comment]
In de [inleiding](https://geonovum.github.io/bmgi/docs/#inleiding-3) heb ik dit onderscheid nu beter omschreven. Graag review @frisopenninga

**Comment by frisopenninga** [comment]
Prima!
