### ISSUE TITLE
Encodings: CRS in GeoJSON - realistisch om alleen WGS te vragen?

### ISSUE THREAD

**Issue by frisopenninga** [Geonovum/bmgi#22]
In https://geonovum.github.io/bmgi/docs/#geojson wordt geadviseerd om alleen WGS84 te gebruiken in GeoJSON. Dit is niet in lijn met de API-strategie (zie https://docs.geostandaarden.nl/api/API-Strategie/#crs-negotiation). Hoewel de eerste lijn zuiverder is vanuit standaardisatie-oogpunt, sluit de lijn uit de API-strategie beter aan bij de praktijk waarin in de NGII juist ook RD en ETRS gevraagd worden in (Geo)JSON.

**Comment by lvdbrink** [comment]
De API strategie redeneert hier teveel vanuit het aanbod IMHO. Ik heb dit nog niet uit de hoofden kunnen krijgen. Het staat overigens in de extensie van de API strategie. 

Ik heb het nu anders opgeschreven, in lijn met OGC API Features: 
> Het coördinaat-referentiesysteem dient, als GeoJSON als formaat wordt gebruikt, bij publicatie voor een onbekend publiek in WGS 84 (EPSG: 4326) te zijn. 

en 
> Als de gegevens worden gepubliceerd op het web maar voor een *bekend* publiek, waarbij de aanbiedende en afnemende partijen een afspraak hebben om een bepaald CRS te gebruiken, is het toegestaan om dezelfde gegevens in GeoJSON ook in andere CRS te publiceren.
