### ISSUE TITLE
Encodings: werkingsgebied GeoJSON

### ISSUE THREAD

**Issue by frisopenninga** [Geonovum/bmgi#23]
https://geonovum.github.io/bmgi/docs/#geojson stelt "Voor gebruik op het web is een nauwkeuriger CRS doorgaans niet nodig. "

Hiermee lijkt het functioneel werkingsgebied van GeoJSON beperkt te worden tot data op het web, terwijl API's vanuit Common Ground ook ingezet kunnen worden in productieketens, bijv. tussen bronhouder en LV. 

Als suggestie:
verbreedt het werkingsgebied, maar doe de aanbeveling voor toepassingen op het web om altijd ook WGS84 aan te bieden (om aan te sluiten bij de praktijk op veel webpagina's)

**Comment by lvdbrink** [comment]
Tekst aangepast, zie [commit](https://github.com/Geonovum/bmgi/commit/a6f5ca837c0c0355f161f86b519787cf96ff0a44)

Review @frisopenninga

**Comment by frisopenninga** [comment]
Top!
