### ISSUE TITLE
Encodings: RDF paragraaf inhoudelijk ook linken aan conceptenbibliotheken?

### ISSUE THREAD

**Issue by frisopenninga** [Geonovum/bmgi#24]
https://geonovum.github.io/bmgi/docs/#rdf Wil je hier ook verwijzen naar concepten in conceptenbibliotheken (als aanbeveling of best practice, om daar je semantiek in vast te leggen)? Of is er juist een goede reden om dat niet te doen?

**Comment by lvdbrink** [comment]
Dit hoofdstuk gaat over het uitwisselen van gegevens, dus ik vind het hier niet op zijn plaats.

Het staat al wel in [15.4 Conceptenbibliotheek](https://geonovum.github.io/bmgi/docs/#conceptenbibliotheek). 

@frisopenninga mijn voorstel is dit niet in de RDF paragraaf op te nemen en dit issue te sluiten. Wil jij dit doen indien akkoord?

**Comment by frisopenninga** [comment]
Goed punt.
