### ISSUE TITLE
Encodings: voordeel GeoPackage ook inzetbaarheid op (offline) mobile

### ISSUE THREAD

**Issue by frisopenninga** [Geonovum/bmgi#25]
https://geonovum.github.io/bmgi/docs/#geopackage Toevoegen dat voordeel is dat formaat geschikt is voor gebruik op mobile devices, ook in offline situaties? (vanuit die gedachte is GeoPackage dacht ik ooit ontstaan)

**Comment by lvdbrink** [comment]
Ik heb de tekst verduidelijkt op dit punt. Zie [commit](https://github.com/Geonovum/bmgi/commit/450f8e83ebabb1cc91188395e34b2aca93d3b84c)

Ter review @frisopenninga

**Comment by frisopenninga** [comment]
Prima
