### ISSUE TITLE
encodings: GeoJSON algemeen

### ISSUE THREAD

**Issue by PalmJanssen** [Geonovum/bmgi#28]
Wordt dit geadresseerd?:

(comment van Paul van Genuchten in INSPIRE alternative encoding).

https://github.com/INSPIRE-MIF/2017.2/blob/master/GeoJSON/geojson-encoding-rule.md

1) Typical use case of geojson is: having 1 featuretype, having 1 geometrytype, having epsg:4326, having no nesting. Any deviation of this will break implementations somewhere.

2) If applying strict geojson, also consider how to guide data providers on how to implement a transformation. For example if a GML has multiple featuretypes and/or geometrytypes, consider to advice to split the file in multiple files. Add a link to each of the files in Metadata or Atom.

A wfs response to a user requesting a simplified format will be more challenging. Maybe provide a zip-file having individual files for featuretypes and geometrytypes?

**Comment by lvdbrink** [comment]
Niet in NEN3610 zelf, maar dit kunnen we wel beschrijven in de nieuwe handreiking over het uitwisselen van geometrie. Zie https://github.com/Geonovum/geox. Ik zal daar het issue ook opvoeren.
