### ISSUE TITLE
Review 9. 3D Modellering

### ISSUE THREAD

**Issue by lvdbrink** [Geonovum/bmgi#63]
- De items in de bullet list zijn in feite aanbevelingen. Ik zou hier dan ook het kopje **Aanbevelingen:** boven zetten. Dit doen we elders in de BMGI tekst ook.
- De inhoud van het stuk gaat over meer dan 3D modellering, althans meer dan _informatie_modellering. De titel is daarom een beetje verwarrend.
- Je zou nog kunnen toevoegen als aandachtspunt dat niet alle encodings 3D ondersteunen, en verwijzen naar de paragraaf die daarover gaat.
- 1 redactionele toevoeging gedaan, zie [commit]
(https://github.com/Geonovum/bmgi/commit/09e08b296c96f6957df69be1ff39576a78b16f9e).

**Comment by lvdbrink** [comment]
Nog één ding: Ik zou dit niet als hfd 9 opnemen maar pas later in het document, bv na Metadata.

**Comment by frisopenninga** [comment]
Alle inhoudelijke punten verwerkt. Hoofdstuk stond 2x in tekst, als hfd. 9 en 18. Nu alleen aan einde.
